import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css'
import { ProductProvider } from "@/hooks/UseProducts";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProductProvider>
        <body className={`${inter.className} flex flex-col flex-1 bg-black min-h-screen`}>
          <header className="text-white flex justify-between items-center px-24 py-6">
            <h1 className="text-3xl">Gestor de Estoque</h1>
            <nav>
              <ul className="flex gap-5 text-lg">
                <li className="hover:text-cyan-500 duration-150"><Link href={`/`}>Novo Produto</Link></li>
                <li className="hover:text-cyan-500 duration-150"><Link href={`/products`}>Produtos</Link></li>
              </ul>
            </nav>
          </header>
          {children}
        </body>
      </ProductProvider>
    </html>
  );
}
